package com.example.Neo4jExample.model;

public enum EventType {

    ACCOMMODATION_CREATED, USER_CREATED, USER_STAYED, RATE_CREATED, USER_CREATE_FAILED,
    RATE_CREATE_FAILED, ACCOMMODATION_CREATE_FAILED, USER_STAY_FAILED, RESERVATION_CANCELED,
    ACCOMMODATION_DELETED, USER_DELETED, RATE_CHANGED, RATE_DELETED
}
